# Generated by Django 2.1.1 on 2018-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20181013_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('appkey', models.CharField(max_length=30)),
            ],
        ),
    ]
