# Generated by Django 2.1.1 on 2018-10-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todoapps'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapps',
            name='canDeleteUsers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoapps',
            name='canMakeUsers',
            field=models.BooleanField(default=False),
        ),
    ]
