# Generated by Django 2.1.2 on 2018-10-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20181017_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapps',
            name='canRequestNonActiveNotes',
            field=models.BooleanField(default=False),
        ),
    ]
