# Generated by Django 2.1.2 on 2018-10-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_todoapps_canrequestnonactivenotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapps',
            name='canActivateNotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoapps',
            name='canDeactivateNotes',
            field=models.BooleanField(default=False),
        ),
    ]
