# Generated by Django 2.1.2 on 2018-11-11 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20181017_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='todonote',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
