# Generated by Django 2.1.2 on 2018-11-11 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todonote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todonote',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
